# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
    vmImage: "macOS-latest"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "10.x"
      displayName: "Install Node.js"

    - script: |
          npm install
      displayName: "npm install"
    - script: |
          npm run lint
      displayName: "npm run lint"
    - script: |
          npm run test
      displayName: "npm run test"
    - script: |
          npm run build
      displayName: "npm run build"
    - script: |
          npm run sync
      displayName: "npm run sync"

    - task: Gradle@2
      inputs:
          workingDirectory: "android"
          gradleWrapperFile: "android/gradlew"
          gradleOptions: "-Xmx3072m"
          tasks: "build"
      displayName: "Android APK > Build"
    - task: AndroidSigning@3
      inputs:
        apkFiles: '**/app-release-unsigned.apk'
        apksignerKeystoreFile: 'upload-keystore.jks'
        apksignerKeystorePassword: 'lead2gold'
        apksignerKeystoreAlias: 'upload'
        apksignerKeyPassword: 'gold2lead'
        zipalign: false
      displayName: "Android APK > Sign"
    - task: CopyFiles@2
      inputs:
          contents: "**/app-release-unsigned.apk"
          flattenFolders: true
          targetFolder: "$(Build.ArtifactStagingDirectory)"
      displayName: "Android APK > Copy to Artifacts"
    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
          publishLocation: "Container"
      displayName: "Android APK > Publish Artifacts"
    # - task: GooglePlayRelease@3
    #   inputs:
    #       serviceConnection: "Google Play K53 Ninja"
    #       apkFile: "**/app-release-unsigned.apk"
    #       track: "internal"
    #   displayName: "Android APK > Copy to Google Play"
